/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as AdvancementsRouteImport } from './routes/advancements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BuildsSlugRouteImport } from './routes/builds.$slug'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancementsRoute = AdvancementsRouteImport.update({
  id: '/advancements',
  path: '/advancements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsRoute,
} as any)
const BuildsSlugRoute = BuildsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BuildsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advancements': typeof AdvancementsRoute
  '/builds': typeof BuildsRouteWithChildren
  '/crafting': typeof CraftingRoute
  '/experience': typeof ExperienceRoute
  '/portal': typeof PortalRoute
  '/skills': typeof SkillsRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds/': typeof BuildsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advancements': typeof AdvancementsRoute
  '/crafting': typeof CraftingRoute
  '/experience': typeof ExperienceRoute
  '/portal': typeof PortalRoute
  '/skills': typeof SkillsRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds': typeof BuildsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advancements': typeof AdvancementsRoute
  '/builds': typeof BuildsRouteWithChildren
  '/crafting': typeof CraftingRoute
  '/experience': typeof ExperienceRoute
  '/portal': typeof PortalRoute
  '/skills': typeof SkillsRoute
  '/builds/$slug': typeof BuildsSlugRoute
  '/builds/': typeof BuildsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advancements'
    | '/builds'
    | '/crafting'
    | '/experience'
    | '/portal'
    | '/skills'
    | '/builds/$slug'
    | '/builds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advancements'
    | '/crafting'
    | '/experience'
    | '/portal'
    | '/skills'
    | '/builds/$slug'
    | '/builds'
  id:
    | '__root__'
    | '/'
    | '/advancements'
    | '/builds'
    | '/crafting'
    | '/experience'
    | '/portal'
    | '/skills'
    | '/builds/$slug'
    | '/builds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancementsRoute: typeof AdvancementsRoute
  BuildsRoute: typeof BuildsRouteWithChildren
  CraftingRoute: typeof CraftingRoute
  ExperienceRoute: typeof ExperienceRoute
  PortalRoute: typeof PortalRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advancements': {
      id: '/advancements'
      path: '/advancements'
      fullPath: '/advancements'
      preLoaderRoute: typeof AdvancementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/builds/$slug': {
      id: '/builds/$slug'
      path: '/$slug'
      fullPath: '/builds/$slug'
      preLoaderRoute: typeof BuildsSlugRouteImport
      parentRoute: typeof BuildsRoute
    }
  }
}

interface BuildsRouteChildren {
  BuildsSlugRoute: typeof BuildsSlugRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
}

const BuildsRouteChildren: BuildsRouteChildren = {
  BuildsSlugRoute: BuildsSlugRoute,
  BuildsIndexRoute: BuildsIndexRoute,
}

const BuildsRouteWithChildren =
  BuildsRoute._addFileChildren(BuildsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancementsRoute: AdvancementsRoute,
  BuildsRoute: BuildsRouteWithChildren,
  CraftingRoute: CraftingRoute,
  ExperienceRoute: ExperienceRoute,
  PortalRoute: PortalRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
